baseURL : 'https://raunaqness.github.io/'
languageCode : 'en-us'
title : 'raunaqness.com'
theme : 'PaperMod'
publishDir : "."
staticDir:
- staticfiles
params:
    defaultTheme: light
    disableThemeToggle: false
    googleAnalytics: "G-WE06JCZYNP"  # Replace with your actual GA4 Measurement ID
    profileMode:
        enabled: false
        title: "Raunaq Singh" # optional default will be site title
        subtitle: "Software Engineer | Consultant | Coffee Enthusiast"
        imageUrl: "/images/bhutan.jpg" # optional
        imageTitle: "dp" # optional

    socialIcons: # optional
        - name: "x"
          url: "https://x.com/raunaqness"
        - name: "instagram"
          url: "https://www.instagram.com/raunaqness/"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/gurraunaqsingh/"
        - name: "medium"
          url: "https://medium.com/@raunaqness"
        - name: "github"
          url: "https://github.com/raunaqness"
        - name: "email"
          url: "mailto:raunaqness@gmail.com"

menu:
  main:
    - name: Projects
      url: /projects
      weight: 10
    - name: Blog
      url: /blog
      weight: 20
    - name: Resume
      url: /resume
      weight: 30
    - name: Photography
      url: /photography
      weight: 40
    - name: Reading
      url: /reading
      weight: 50
    - name: Contact
      url: /contact
      weight: 60

markup:
  goldmark:
    renderer:
      unsafe: true
